# Generated by Django 3.0.3 on 2020-06-24 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Praca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zdjecie', models.ImageField(upload_to='media')),
                ('nazwa', models.CharField(max_length=250)),
                ('opis', models.TextField()),
            ],
        ),
    ]
