# Generated by Django 3.0.3 on 2020-06-25 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='praca',
            name='czas_pracy',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
    ]
