# Generated by Django 3.0.3 on 2020-06-27 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_content', '0002_praca_czas_pracy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zdjecie', models.ImageField(upload_to='media')),
                ('nazwa', models.CharField(max_length=250)),
                ('dosw_prywatne', models.CharField(max_length=250)),
                ('dosw_zawodowe', models.CharField(max_length=250)),
                ('opis', models.TextField()),
            ],
        ),
    ]
